INSERT INTO ch_channel (CHANNEL_CODE, CHANNEL_CN_NAME, CHANNEL_TYPE, CHANNEL_BK_DESC, BACKUP_FLD, RCD_STATE) VALUES ('01', 'PCWEB∂À', 1, 'PCWEB∂ÀΩ”»Î«˛µ¿', null, 1);
INSERT INTO ch_channel (CHANNEL_CODE, CHANNEL_CN_NAME, CHANNEL_TYPE, CHANNEL_BK_DESC, BACKUP_FLD, RCD_STATE) VALUES ('02', 'IOS∂À', 3, 'IOS∂À', null, 1);
