INSERT INTO us_user_role (USER_ID, DPRL_CODE, USER_BK_WEIGHT, BACKUP_FLD) VALUES ('admin', '11000101', 1, null);
INSERT INTO us_user_role (USER_ID, DPRL_CODE, USER_BK_WEIGHT, BACKUP_FLD) VALUES ('account', '11000101', 6, null);
